spring.application.name=application-platform


spring.datasource.url=jdbc:postgresql://localhost:5433/application_platform
spring.datasource.username=platform_user
spring.datasource.password=platform_password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration