

spring.application.name=application-platform

server.port=${SERVER_PORT:8080}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/application_platform}
spring.datasource.username=${DB_USERNAME:platform_user}
spring.datasource.password=${DB_PASSWORD:platform_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# JWT
jwt.secret=${JWT_SECRET:gfhgdfvbnidosd1fvbbfdneiwosldcv3dnosldcmv2fdsp}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.root=INFO
logging.level.com.vijay.platform=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{requestId}] %logger{36} - %msg%n


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never

management.info.env.enabled=true

info.app.name=Application Platform
info.app.description=Reusable application foundation
info.app.version=1.0.0