spring.application.name=application-platform


spring.datasource.url=jdbc:postgresql://localhost:5432/application_platform
spring.datasource.username=platform_user
spring.datasource.password=platform_password

spring.datasource.driver-class-name=org.postgresql.Driver